### ISSUE TITLE
Suggestion: Both modes - Head mode and Sponge mode

### ISSUE THREAD

**Issue by FakeKoktis** [I2000C/NewAmazingLuckyBlocks#15] opened 2021-11-22 16:48 UTC
Please, add a possibility to make both modes enabled if it's possible...
I will be really thankful for that...

**Comment by I2000C** [comment] 2021-11-22 18:28
Yes, it would be possible.
However, why do you want to use both modes at the same time?

**Comment by FakeKoktis** [comment] 2021-11-22 19:48
I want it because I'm using it with SkyWars plugin, that plugin doesn't support these lucky blocks (heads) in chests, so sponge is the easiest way for it...

**Comment by FakeKoktis** [comment] 2021-11-22 19:48
And I'm using these heads on SkyWars islands...

**Comment by I2000C** [comment] 2021-11-22 19:52
I understand now.
I will add an option to do that in the next version.
However, you will have to wait a bit since I'm very busy these weeks.

**Comment by I2000C** [comment] 2021-11-28 18:43
Check this version when you can:
[NewAmazingLuckyBlocks (both issue).zip](https://github.com/I2000C/NewAmazingLuckyBlocks/files/7614126/NewAmazingLuckyBlocks.both.issue.zip)

I think the problem is solved with that version.
You need to change the HeadMode option to 'both' in order to detect both heads and sponges
(i.e. change the 'true' or 'false' value to 'both')

If the problem is solved, close the issue.

**Closed as completed** 2021-12-24 10:11 UTC
Labels: future feature
